### ISSUE TITLE
Stream incomplete values

### ISSUE THREAD

**Issue by chrisciszak** [juanjoDiaz/streamparser-json#31]
Hey @juanjoDiaz 

Is it possible to stream incomplete values? Currenly both OnToken and onValue will provide full tokens or attributes. However, I want to be able to easily access given string value before it is fully complete. It would need an artificial closing quote dynamically generated until the end closing quote finally arrives.

Any idea how to do it?

**Comment by juanjoDiaz** [comment]
Can you elaborate a bit on the need?
Why would you need an incomplete value?
`{ "a": "asdf` means nothing if it's finished.

Currently, streamparser/json receives a binary array. When it detects a string token start (opening `"`) it starts accumulating the binary form of a string in a buffer until it's completed (closing `"`). Then it encoded it to an actual string and emits it.

**Comment by chrisciszak** [comment]
@juanjoDiaz thank you for a quick reply. 

Trying to make this plugin more AI friendly which is one of the reasons I think your plugin is gaining traction this year. The use case is that usually it takes a while for AI to generate content. In order to make the users experience better, we stream the data to the user so they can read it as it is being generated. 

`{ "a": "asdf` means nothing on its own, but as the text is being streamed, the content keeps expanding and it starts having a meaning to the user.

**Comment by chrisciszak** [comment]
one of the requirement that would make it easier to work with would be to only make the incomplete value output, not the name of the attribute itself.

Also is there ability to actually get access to the whole JSON document as it is being generated rather than subscribing to onToken or onValue

**Comment by chrisciszak** [comment]
I think what we really could do with is onValueUpdate which would have the same input params that the current onValue function has.

**Comment by juanjoDiaz** [comment]
Let's see...

JSON parsing is composed of 2 steps: tokenizing and parsing.

Tokenizing is the step in which a string (or the binary representation of a string) is parsed into tokens. A token can be a string, a boolean, a null, braces, backets, colon, comma, etc.

Parsing process the tokens to reassemble the JSON object.

`onToken` emits the results of parsed tokens.
Until the point when the token is emitted, there is no way to know if the token is valid.
Imagine `{ "a": 123456.a }` and print `onToken`:

```ks
{token: 0, value: "{", offset: 0}
{token: 9, value: "a", offset: 2}
{token: 4, value: ":", offset: 5}
TokenizerError: Unexpected "a" at position "14" in state NUMBER_AFTER_FULL_STOP
```

It doesn't make sense in my opinion to emit data until you know where it is valid or not.

`onValue` emit JSON (array, object, string, number, bool, null, ...) as tokens are parsed
Until the point when the JSON is emitted, there is no way to know if the token is valid.
Imagine `{ "a": 123456,  null : 2 }`  and print `onValue`:

```js
{value: 123456, key: "a", parent: Object {a: 123456}, …}
TokenParserError: Unexpected NULL (null) in state KEY
```

Similarly, it doesn't make sense to emit values until you know that they are valid.

So, in my opinion, you can get all the partial information available during the parsing process as long as such information is guaranteed to be valid.

Furthermore emitting partial information will have additional performance impact that I would like to avoid.

I'd be happy to hear more use case for this and I could reconsider. But this seems really like an edge case.


That said, I would say that you are putting long strings in your JSON, don't want to wait for it to complete parsing and don't care of where the string is correct or it will fail.

So, let me try to help you with that.
Luckily for you, javascript doesn't have private properties/methods. So, you can use the internals for this.

Every call to `write` is synchronous. So after every write, you could check if there is a string in the middle

```js
const { JSONParser } = require("@streamparser/json");

const parser = new JSONParser();
parser.onValue = console.log;

parser.write('{ "a": "asdfgasdgafgadfgasdfasdf');
console.log(getInParsingString(parser))

function getInParsingString(parser) {
    if (parser.tokenizer.state !== 13) return; // Parsing something else than a string
    return parser.tokenizer.bufferedString.toString();
}
```

This is abusing this library internals and I don't guarantee that it will ever change. But it's pretty stable at the moment.

Hope this helps!

**Comment by chrisciszak** [comment]
Hey @juanjoDiaz  thank you for the workaround! Do you see any clean way to collect the key for the parsing string? It doesn't seem to be populate on the tokenParser for some reason.

![image](https://github.com/juanjoDiaz/streamparser-json/assets/11364221/40ee55e8-ff98-410a-aef6-3838f80d6546)

**Comment by chrisciszak** [comment]
Apologies, it wasn't printing to console but actually Im able to retrieve it. Thank you!
