### ISSUE TITLE
Dist files are using `export * ...` fails to compile with webpack 4

### ISSUE THREAD

**Issue by zibra** [juanjoDiaz/streamparser-json#34]
Error from: @streamparser/json/dist/mjs/index.js 4:9

![obraz](https://github.com/juanjoDiaz/streamparser-json/assets/4493100/afb7c553-52c4-491b-a836-1603bd16dc5f)

**Comment by juanjoDiaz** [comment]
Hi @zibra ,

There are plenty of people out there using this package with webpack.
As the error says, it looks like your compiler is doing misconfigured somehow.

If you are using es6 modules, then it's expected that `dist/mjs` modules are used.
If you are using commonjs modules, then it's expected that `dist/cjs` modules are used.
I don't see any issue based on the info that you have provided.

**Comment by defghy** [comment]
webpack 4 not support "export * as..." syntax; webpack 5 support it
https://stackoverflow.com/questions/74717884/webpack-cannot-compile-file-that-uses-export-as-something

**Comment by defghy** [comment]
if you use vue-cli-service, this is solution
- use this babel plugin
https://babeljs.io/docs/babel-plugin-transform-export-namespace-from
 - compile node_modules
 ```
// vue.config.js
{
...
  transpileDependencies: [/@streamparser\/json/],
}
```
