### ISSUE TITLE
OptimisticJSONParser not found

### ISSUE THREAD

**Issue by kenn** [juanjoDiaz/streamparser-json#38]
However it's documented in [the doc](https://www.npmjs.com/package/@streamparser/json) with [this commit](https://github.com/juanjoDiaz/streamparser-json/commit/9fbc16f9681a29bbcb57325b90620ce1f78c20e0), `OptimisticJSONParser` is nowhere to be found.

Any plans to materialize it?

<img width="808" alt="Screenshot 2023-12-14 at 9 55 06 PM" src="https://github.com/juanjoDiaz/streamparser-json/assets/10350/46f6327f-d159-4ab9-8a24-aefb91c62f06">

**Comment by juanjoDiaz** [comment]
That's an oversight from my part.

`OptimisticParser` is not part of the library.
Instead, we have the `emitPartialTokens` and `emitPartialValues` options as shown in https://www.npmjs.com/package/@streamparser/json#stream-parsing-a-fetch-request-returning-a-very-long-string-getting-previews-of-the-string.

I'll fix the documentation today with a new release.
