### ISSUE TITLE
Potential performance improvement

### ISSUE THREAD

**Issue by oliverfoster** [juanjoDiaz/streamparser-json#39]
https://github.com/juanjoDiaz/streamparser-json/blob/cda44fb20219947db5452e65e9cc9d8d0ecfb3e0/packages/plainjs/src/tokenizer.ts#L158

```js
const l = buffer.length
for (let i = 0; i < l; i += 1) { 
```

**Comment by juanjoDiaz** [comment]
Hi @oliverfoster ,

Have you run some performance testing using your improvement?

In general, JavaScript is excellent inlining values that don't change and optimizing code at runtime, so this kind of micro-optimization that could make a difference in other languages tends to make no difference in javascript.

**Comment by oliverfoster** [comment]
![image](https://github.com/juanjoDiaz/streamparser-json/assets/7974663/ef88f169-1cf2-4688-8996-8762717c5360)

![image](https://github.com/juanjoDiaz/streamparser-json/assets/7974663/5fd40082-4d9d-4433-97ce-1201b634834c)

In node stand corrected, apologies.

Weirdly it's different in browsers with arrays.
https://www.measurethat.net/Benchmarks/Show/2/1/caching-length-property-vs-getting-it-each-time-in-the

![image](https://github.com/juanjoDiaz/streamparser-json/assets/7974663/7a1e8c04-e716-4639-be1e-964574e248ad)

Thanks for pushing back and for the response and the libraries.
