### ISSUE TITLE
Add support for Node streams

### ISSUE THREAD

**Issue by juanjoDiaz** [juanjoDiaz/streamparser-json#5]

**Comment by dandv** [comment]
Was looking for a package to stream a large JSON files. Looks like this isn't supported yet?

If it is, an [example](https://github.com/juanjoDiaz/streamparser-json/tree/main/packages/plainjs#examples) would help 🙏

**Comment by juanjoDiaz** [comment]
I also published https://www.npmjs.com/package/@streamparser/json-node

That's just a node Transform stream wrapper of JSON parser 😁

If you need help on how to use it. Just ask 🙂
